/**
 * 操作手册（纯文本，用换行符排版）。
 *
 * /prompts 命令输出会在聊天框按纯文本展示：markdown 与 HTML 均无法解析，
 * 因此这里用普通字符串 + 换行符组织内容，中英双语并存于同一模块。
 */
export const manualZh = [
  "dsh-prompt-library 提示词库 — 使用手册",
  "==========================================",
  "",
  "【一、这是什么插件】",
  "内置于聊天界的提示词管理工具，帮你系统性地保存、整理、检索和复用优质提示词。主要由三部分组成：",
  "- 侧边栏提示词库：右侧固定宽度面板，浏览、搜索、管理所有已保存的提示词；",
  "- 聊天框提示词按钮：输入框旁的一键入口，随时插入或复制提示词；",
  "- Slash 命令：输入 /prompts 开头的命令，直接保存、AI 润色或用 AI 补齐新提示词。",
  "所有数据存在本地 SQLite（~/.dsh/prompt-library/db/prompts.db），不上传云端，导出/导入备全都自控。",
  "",
  "【二、核心命令】",
  "（/prompts 后务必加一个空格再输入）",
  "/prompts <正文>          把正文保存到词库，AI 自动生成标题与标签",
  "/prompts -AI <正文>     对 <正文> 做 AI 润色，结果填充回输入框（-AI/-ai/-a/-A 均可）",
  "/prompts -h              显示本手册（-help/--help 亦可）",
  "",
  "保存时的行为：",
  "- 正文为空会拦截提示，不会保存；",
  "- 与已有提示词重复时直接复用，不制造冗余；",
  "- 保存后所有用到提示词的地方（侧边栏、聊天框面板、词库管理）自动刷新。",
  "",
  "【三、侧边栏提示词库】",
  "- 分组浏览：按「最近使用」「标签」「未分类」分组，同一提示词可同时出现在最近使用与其标签分组；",
  "- 搜索：顶部输入关键词实时过滤，命中标题与正文的关键词高亮显示；",
  "- 标签过滤：点击标签芯片可与关键词搜索叠加筛选；",
  "- 插入：点击某条提示词，其正文会按需做变量（{{变量}}）填充后插入聊天框；",
  "- 常见操作：插入、复制、覆盖原文、编辑、软删除（进回收站）；",
  "- 悬停详情：在条目上停留片刻，左侧滑出详情卡片便于快速浏览。",
  "",
  "【四、聊天框提示词按钮】",
  "- 一键打开最近使用/常用提示词列表，直接插入当前会话；",
  "- 工具栏选中文本后可用 AI 润色（此入口不处理 {{}} 变量）。",
  "",
  "【五、变量模板】",
  "- 正文可用 {{变量名}} 占位，例如：请用{{语气}}的语气，向{{读者}}介绍{{主题}}。；",
  "- 插入时弹出填充界面，自动记忆上次填过的值，同变量名下次自动带出。",
  "",
  "【六、AI 能力】",
  "- AI 智能完善：保存后自动提炼标题、标签与摘要；",
  "- AI 润色：打磨选中文本。聊天框入口不保留 {{}} 变量，其他入口（侧边栏、确认卡）默认保留并可新增；",
  "- 自动学习：较长正文可经 /prompts 一键入库，是否手动确认可在设置调整。",
  "",
  "【七、数据管理（设置 → 词库管理）】",
  "- 导入/导出：可勾选范围导出为备份，也可导入恢复；",
  "- 标签管理：统一新建、重命名、删除；正在被使用的标签禁止删除（会提示当前用量）；",
  "- 回收站：软删除的提示词在此，支持单条或批量「恢复/永久删除」；",
  "- 删除确认：涉及删除的操作使用自定义确认弹窗，避免误删。",
  "",
  "【八、常见问题】",
  "Q：保存后面板没变化？",
  "A：确认已重启 dsh web 使新版本生效；保存后会自动刷新所有面板。",
  "",
  "Q：/prompts -AI 没反应？",
  "A：AI 润色依赖可用的大模型，若提示「AI 服务不可用」请检查模型配置。",
  "",
  "Q：数据存在哪里？会不会丢？",
  "A：本地 SQLite（~/.dsh/prompt-library/db/prompts.db），建议定期用「词库管理 → 导出」备份。",
  "",
  "Q：标签删不掉？",
  "A：该标签正被提示词使用，请先移除或到词库管理清理；保护机制会阻止删除在用标签。",
].join("\n");

export const manualEn = [
  "dsh-prompt-library — User Manual",
  "================================",
  "",
  "[1. What This Plugin Is]",
  "A prompt management tool built into the chat interface. It saves, organizes, searches, and reuses the prompts you use often. Main parts:",
  "- Sidebar prompt library: fixed-width right panel to browse, search, and manage all prompts;",
  "- Chat-box prompt button: a one-click entry beside the input box to insert or copy a prompt;",
  "- Slash commands: type /prompts-prefixed commands to save, AI-polish, or let AI fill in a prompt.",
  "Everything runs locally (SQLite at ~/.dsh/prompt-library/db/prompts.db); nothing is uploaded to the cloud.",
  "",
  "[2. Core Commands]",
  "(Remember the space after /prompts)",
  "/prompts <body>          Save the body; AI generates title and tags",
  "/prompts -AI <body>     AI-polish the body and fill the result into the input box (-AI/-ai/-a/-A all work)",
  "/prompts -h              Show this manual (-help/--help also work)",
  "",
  "When saving:",
  "- Empty input is blocked with a hint and not saved;",
  "- A duplicate body is reused instead of duplicated;",
  "- After saving, every place using prompts (sidebar, chat-box panel, data management) refreshes automatically.",
  "",
  "[3. Sidebar Prompt Library]",
  "- Grouped browsing: Recently used / Tags / Uncategorized; a prompt can appear under both Recently used and its tag group;",
  "- Search: type a keyword for live filtering; matches in titles and bodies are highlighted;",
  "- Tag filter: click tag chips to stack on top of keyword search;",
  "- Insert: click a prompt to insert its body into the chat box after variable ({{variable}}) filling;",
  "- Common actions: insert, copy, overwrite, edit, soft delete (to recycle bin);",
  "- Hover detail: hover an item briefly to slide out a detail card on its left.",
  "",
  "[4. Chat-box Prompt Button]",
  "- One-click to open the Recently used / common prompts list and insert into the current session;",
  "- Select text in the toolbar and invoke AI polish (this entry does not process {{}} variables).",
  "",
  "[5. Variable Templates]",
  "- Use {{variableName}} placeholders, e.g.: Explain {{topic}} to {{audience}} in a {{tone}} tone.;",
  "- The fill dialog remembers the last value you filled per variable name, so it is filled in automatically next time.",
  "",
  "[6. AI Capabilities]",
  "- AI enrichment: automatically extracts title, tags, and summary after saving;",
  "- AI polish: refines selected text. The chat-box entry does not preserve {{}} variables; other entries keep them and can add new ones;",
  "- Auto-learn: save longer bodies with one command; whether manual confirm is enabled is set in settings.",
  "",
  "[7. Data Management (Settings → Data management)]",
  "- Import / export: export a selected scope as a backup, or import to restore;",
  "- Tag management: create, rename, delete; tags in use cannot be deleted (the usage count is shown);",
  "- Recycle bin: soft-deleted prompts are here; restore or permanently delete single items or in bulk;",
  "- Delete confirmation: delete operations use a custom confirm dialog to avoid accidents.",
  "",
  "[8. FAQ]",
  "Q: Why doesn't the panel update after saving?",
  "A: Make sure you restarted dsh web so the new version takes effect; panels refresh automatically after saving.",
  "",
  "Q: /prompts -AI does nothing?",
  "A: AI polishing depends on an available model; if you see \"AI service is unavailable\", check your model config.",
  "",
  "Q: Where is my data? Could it be lost?",
  "A: It lives in local SQLite (~/.dsh/prompt-library/db/prompts.db); back it up via Data management → Export regularly.",
  "",
  "Q: Why can't I delete a tag?",
  "A: The tag is in use by some prompts. Remove it from those prompts first, or clean up via data management; the protection blocks deleting in-use tags.",
].join("\n");