/**
 * 操作手册（纯文本，用换行符排版）。
 *
 * /prompts 命令输出会在聊天框按纯文本展示：markdown 与 HTML 均无法解析，
 * 因此这里用普通字符串 + 换行符组织内容，中英双语并存于同一模块。
 *
 * 本手册仅用于 /prompts -h 与欢迎引导，不再经系统 prompt 注入打印到聊天框；
 * 会话上下文由 HARNESS 文件（~/.dsh/prompt-library/prompts/HARNESS.md）提供。
 */
export const manualZh = [
  "dsh-prompt-library 词库 — 使用手册",
  "==========================================",
  "",
  "【一、这是什么插件】",
  "内置于聊天界的提示词管理工具，帮你系统性地保存、整理、检索和复用优质提示词。主要由三部分组成：",
  "- 侧边栏词库：右侧固定宽度面板（可展开/折叠），浏览、搜索、管理所有已保存的提示词；",
  "- 聊天框提示词按钮：输入框旁的一键入口，随时插入或复制提示词；选中文字可直接 AI 润色；",
  "- Slash 命令：输入 /prompts 开头的命令，直接保存、AI 润色或用 AI 补齐新提示词。",
  "所有数据存在本地 SQLite（~/.dsh/prompt-library/db/prompts.db），不上传云端，导出/导入备份都由你掌控。",
  "",
  "【二、核心命令】",
  "（/prompts 后务必加一个空格再输入；命令不区分大小写，支持简化别名）",
  "- /prompts -add <正文>：保存正文，AI 自动生成标题与标签（别名 -ad）",
  "- /prompts -tag <标签> <正文>：按指定标签保存（别名 -t）",
  "- /prompts -s <关键词>：检索词库，标题/正文匹配，大小写不敏感",
  "- /prompts -enrich <正文>：AI 专业完善（别名 -en），扩写为更专业/全面/结构完整的版本，结果打印在聊天返回、自行复制",
  "- /prompts -e：导出全部提示词（别名 -exp，纯文本，可直接复制）",
  "- /prompts -data：输出实时统计 + 最近 7 天历史快照，末尾附 AI 点评（别名 -d）",
  "- /prompts -AI <正文>：对正文做 AI 润色（别名 -a），结果打印在聊天返回、自行复制",
  "- /prompts -h：显示本手册（-help/--help 亦可）",
  "- /prompts：单独输入，列出全部可用命令示例",
  "",
  "保存时的行为：",
  "- 正文为空会拦截提示，不会保存；",
  "- 与已有提示词重复时直接复用，不制造冗余；",
  "- 保存后所有用到提示词的地方（侧边栏、聊天框面板、词库管理）自动刷新。",
  "",
  "【三、侧边栏词库】",
  "- 展开/折叠：点击面板顶部的按钮可收起为边缘小按钮，再次点击恢复，不影响聊天；",
  "- 分组浏览：按「最近使用」「标签」「未分类」分组，同一提示词可同时出现在最近使用与其标签分组；",
  "- 搜索：顶部输入关键词实时过滤，命中标题与正文的关键词高亮显示；",
  "- 标签过滤：点击标签芯片可与关键词搜索叠加筛选；",
  "- 插入：点击某条提示词，其正文会按需做变量（{{变量}}）填充后插入聊天框；",
  "- 常见操作：插入、复制、覆盖原文、编辑、软删除（进回收站）；",
  "- 悬停详情：在条目上停留片刻，左侧滑出详情卡片便于快速浏览（可在设置中关闭）。",
  "",
  "【四、聊天框提示词按钮】",
  "- 一键打开最近使用/常用提示词列表，直接插入当前会话；",
  "- 输入 # 触发词库选择：继续输入可实时筛选，↑↓ 选择、回车插入，空格或 Esc 结束（可在设置中关闭）；",
  "- 工具栏选中文本后可用 AI 润色（此入口不处理 {{}} 变量）；",
  "- 选中添加提示词（默认关闭，可在设置开启）：在聊天内容中高亮选中文字，浮出「添加提示词」按钮，独立窗口填写标题/标签/正文后保存，也可直接复制选中文字。",
  "",
  "【五、变量模板】",
  "- 正文可用 {{变量名}} 占位，例如：请用{{语气}}的语气，向{{读者}}介绍{{主题}}。；",
  "- 插入时弹出填充界面，自动记忆上次填过的值，同变量名下次自动带出。",
  "",
  "【六、AI 能力】",
  "- AI 智能完善：保存后自动提炼标题、标签与摘要，并在词库内优化改写正文；",
  "- AI 润色：打磨选中文本。聊天框入口不保留 {{}} 变量，其他入口（侧边栏、确认卡）默认保留并可新增；",
  "- 自动学习（默认关闭）：输入较长正文并停顿片刻后自动保存到词库，可开启手动确认后再入库，并可选调用 AI 智能完善。",
  "",
  "【七、数据与统计】",
  "- 导入/导出：可在设置 → 词库管理中勾选范围导出为备份，也可导入恢复；",
  "- 标签管理：统一新建、重命名、删除；正在被使用的标签禁止删除（会提示当前用量）；",
  "- 回收站：软删除的提示词在此，支持单条或批量「恢复/永久删除」；",
  "- 每周自动统计：每 7 天自动生成一次「近 7 天」的增量统计快照（新增/使用/AI 完善），在 /prompts -data 结尾展示，不会重复统计；",
  "- 删除确认：涉及删除的操作使用自定义确认弹窗，避免误删。",
  "",
  "【八、人格（实验室功能）】",
  "- 人格文件：~/.dsh/prompt-library/character/SOUL.md，聚合身份、性格/语气、工作规范；",
  "- 内容需手动填写维护，形成稳定的助手人格；被删除的文件会在下次启动时自动重建为默认模板；",
  "- 在设置中勾选「整个聊天应用人格」后，会约束之后新建的会话（不影响进行中的对话）。",
  "",
  "【九、常见问题】",
  "Q：保存后面板没变化？",
  "A：确认已重启 dsh web 使新版本生效；保存后会自动刷新所有面板。",
  "",
  "Q：/prompts -AI 没反应？",
  "A：AI 润色依赖可用的大模型，若提示「AI 服务不可用」请检查模型配置。",
  "",
  "Q：数据存在哪里？会不会丢？",
  "A：本地 SQLite（~/.dsh/prompt-library/db/prompts.db），建议定期用「词库管理 → 导出」备份。",
  "",
  "Q：标签删不掉？",
  "A：该标签正被提示词使用，请先移除或到词库管理清理；保护机制会阻止删除在用标签。",
].join("\n");

export const manualEn = [
  "dsh-prompt-library — User Manual",
  "================================",
  "",
  "[1. What This Plugin Is]",
  "A prompt management tool built into the chat interface. It saves, organizes, searches, and reuses the prompts you use often. Main parts:",
  "- Sidebar prompt library: fixed-width right panel (collapsible) to browse, search, and manage all prompts;",
  "- Chat-box prompt button: a one-click entry beside the input box to insert or copy a prompt; select text to AI-polish it;",
  "- Slash commands: type /prompts-prefixed commands to save, AI-polish, or let AI fill in a prompt.",
  "Everything runs locally (SQLite at ~/.dsh/prompt-library/db/prompts.db); nothing is uploaded to the cloud; export/import backups are fully under your control.",
  "",
  "[2. Core Commands]",
  "(Remember the space after /prompts; commands are case-insensitive with short aliases)",
  "- /prompts -add <body>: save the body; AI generates title and tags (alias -ad)",
  "- /prompts -tag <tag> <body>: save with a specific tag (alias -t)",
  "- /prompts -s <keyword>: search the library, matching title/body, case-insensitive",
  "- /prompts -enrich <body>: AI professional enrichment (alias -en), expand into a more professional/complete/structured version; result printed in chat for you to copy",
  "- /prompts -e: export all prompts (alias -exp; plain text, ready to copy)",
  "- /prompts -data: realtime stats + last-7-days history snapshot + AI comment (alias -d)",
  "- /prompts -AI <body>: AI-polish the body (alias -a); result printed in chat for you to copy",
  "- /prompts -h: show this manual (-help/--help also work)",
  "- /prompts: type it alone to list all available command examples",
  "",
  "When saving:",
  "- Empty input is blocked with a hint and not saved;",
  "- A duplicate body is reused instead of duplicated;",
  "- After saving, every place using prompts (sidebar, chat-box panel, data management) refreshes automatically.",
  "",
  "[3. Sidebar Prompt Library]",
  "- Expand / collapse: click the button on top to collapse the panel to an edge button; click again to restore, without affecting the chat;",
  "- Grouped browsing: Recently used / Tags / Uncategorized; a prompt can appear under both Recently used and its tag group;",
  "- Search: type a keyword for live filtering; matches in titles and bodies are highlighted;",
  "- Tag filter: click tag chips to stack on top of keyword search;",
  "- Insert: click a prompt to insert its body into the chat box after variable ({{variable}}) filling;",
  "- Common actions: insert, copy, overwrite, edit, soft delete (to recycle bin);",
  "- Hover detail: hover an item briefly to slide out a detail card on its left (can be disabled in settings).",
  "",
  "[4. Chat-box Prompt Button]",
  "- One-click to open the Recently used / common prompts list and insert into the current session;",
  "- Type # to trigger library selection: keep typing to filter live, ↑↓ to select, Enter to insert, Space or Esc to finish (can be disabled in settings);",
  "- Select text in the toolbar and invoke AI polish (this entry does not process {{}} variables);",
  "- Selection add prompt (off by default, enable in settings): highlight text in the chat, an \"Add prompt\" button floats up; fill title/tags/body in a separate window to save, or copy the selection directly.",
  "",
  "[5. Variable Templates]",
  "- Use {{variableName}} placeholders, e.g.: Explain {{topic}} to {{audience}} in a {{tone}} tone.;",
  "- The fill dialog remembers the last value you filled per variable name, so it is filled in automatically next time.",
  "",
  "[6. AI Capabilities]",
  "- AI enrichment: automatically extracts title, tags, and summary after saving, and refines the body inside the library;",
  "- AI polish: refines selected text. The chat-box entry does not preserve {{}} variables; other entries keep them and can add new ones;",
  "- Auto-learn (off by default): after typing a longer body and pausing, it is saved to the library automatically; optional manual confirm before saving, optionally with AI enrichment.",
  "",
  "[7. Data & Stats]",
  "- Import / export: export a selected scope as a backup, or import to restore, in Settings → Data management;",
  "- Tag management: create, rename, delete; tags in use cannot be deleted (the usage count is shown);",
  "- Recycle bin: soft-deleted prompts are here; restore or permanently delete single items or in bulk;",
  "- Weekly auto-stats: every 7 days a snapshot of the last-7-days increments (added/used/AI-refined) is generated and shown at the end of /prompts -data; no double counting;",
  "- Delete confirmation: delete operations use a custom confirm dialog to avoid accidents.",
  "",
  "[8. Personality (Lab Feature)]",
  "- Personality file: ~/.dsh/prompt-library/character/SOUL.md, combining identity, tone, and work guidelines;",
  "- Fill it in manually to form a stable assistant personality; a deleted file is rebuilt with the default template on the next startup;",
  "- Enable \"Apply personality to the whole chat\" in settings to constrain new conversations (does not affect ongoing ones).",
  "",
  "[9. FAQ]",
  "Q: Why doesn't the panel update after saving?",
  "A: Make sure you restarted dsh web so the new version takes effect; panels refresh automatically after saving.",
  "",
  "Q: /prompts -AI does nothing?",
  "A: AI polishing depends on an available model; if you see \"AI service is unavailable\", check your model config.",
  "",
  "Q: Where is my data? Could it be lost?",
  "A: It lives in local SQLite (~/.dsh/prompt-library/db/prompts.db); back it up via Data management → Export regularly.",
  "",
  "Q: Why can't I delete a tag?",
  "A: The tag is in use by some prompts. Remove it from those prompts first, or clean up via data management; the protection blocks deleting in-use tags.",
].join("\n");
